### ISSUE TITLE
How can I download version 0.4.8?

### ISSUE THREAD

**Issue by xiaolongwu0713** [Strypsteen/Gumbel-Channel-Selection#1]
Hi, how can I download 0.4.8? The current version is 0.5 and I did't find any older version tag.

**Comment by Strypsteen** [comment]
You can find the older version at https://robintibor.github.io/braindecode/ (pip install https://github.com/TNTLFreiburg/braindecode/archive/master.zip).

**Comment by xiaolongwu0713** [comment]
I will try now. Thanks for your work by the way.
